version: "2.4"

# Generate traffic by hitting http://localhost:8081
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    environment:
      BACKEND_URL: "http://backend:9000"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      - backend

  nginx:
    image: traceableai-docker.jfrog.io/traceable/ai.traceable.agent/nginx-1.19.0:0.1.34
    ports:
      - 4050:4050
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST: "mysql"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  # use this if you want to report to an actual traceable env.
  #hypertrace-collector:
  #  image: traceableai-docker.jfrog.io/traceable/oc-collector:0.1.77
  #  container_name: hypertrace-collector
  #  command:
  #    [
  #      "/occollector_linux",
  #      "--config=/conf/collector-config.yaml",
  #      "--logging-exporter",
  #    ]
  #  ports:
  #    - 9411:9411
  #  environment:
  #    - TRACEABLEAI_TOKEN=${TRACEABLEAI_TOKEN}
  #  volumes:
  #    - ./configs/collector.yaml:/conf/collector-config.yaml:ro
