version: "2.4"

# Generate traffic by hitting http://localhost:8081
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    environment:
      BACKEND_URL: "http://nginx:4050"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      - nginx

  nginx:
    image: traceableai-docker.jfrog.io/traceable/ai.traceable.agent/nginx-1.19.0:0.1.34
    ports:
      - 4050:4050
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST: "mysql"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
