version: "2.4"

# Generate traffic by hitting http://localhost:8081
services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST: "mysql"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    environment:
      BACKEND_HOST: "backend"
      HT_REPORTING_ADDRESS: "hypertrace-collector"
    depends_on:
      - backend

  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
