log-level: debug
receivers:
  zipkin: {}
  jaeger: {}
  opencensus:
    keepalive:
      server-parameters:
        max-connection-age: 120s
        max-connection-age-grace: 30s
queued-exporters:
  jaeger:
    # num-workers is the number of queue workers that will be dequeuing batches and sending them out (default is 10)
    # num-workers: 10

    # queue-size is the maximum number of batches allowed in the queue at a given time (default is 5000)
    # queue-size: 5000

    # retry-on-failure indicates whether queue processor should retry span batches in case of processing failure (default is true)
    # retry-on-failure: true

    # backoff-delay is the amount of time a worker waits after a failed send before retrying (default is 5 seconds)
    # backoff-delay: 5s

    # sender-type is the type of sender used by this processor
    sender-type: jaeger-thrift-http

    jaeger-thrift-http:
      collector-endpoint: "https://api-dev.traceable.ai:14268/api/traces"
      timeout: 5s
      iam-endpoint: "api-dev.traceable.ai:443"
global:
  attributes:
    proto-decoder:
      enabled: false
      strip-encoded-tag: false
    enduser:
      - conditions:
          - key: http.url
            regex: \/loginservice\/login
        id_paths:
          - $.user.email
        key: http.response.body
        role_paths:
          - $.user.role
        session_paths:
          - $.token
        type: json
    pii-filter:
      complex-data:
        - key: http.request.body
          type-key: http.request.header.content-type
        - key: http.response.body
          type-key: http.response.header.content-type
        - key: sql.query
          type: sql
        - key: http.url
          type: urlencoded
        - key: http.request.header.cookie
          type: cookie
        - key: http.response.header.set-cookie
          type: cookie
        - key: rpc.request.body
          type: json
        - key: rpc.response.body
          type: json
      key-regexs:
        - category: auth
          redaction-strategy: hash
          regex: ^authorization(\[\d+\])?$
          session-identifier: true
        - category: auth
          redaction-strategy: hash
          regex: ^remember_token(\[\d+\])?$
          session-identifier: true
        - category: auth
          redaction-strategy: hash
          regex: ^session(\[\d+\])?$
          session-identifier: true
        - category: auth
          regex: ^access_token(\[\d+\])?$
        - category: auth
          regex: ^api_key(\[\d+\])?$
        - category: auth
          regex: ^apikey(\[\d+\])?$
        - category: auth
          regex: ^password(\[\d+\])?$
        - category: auth
          regex: ^passwd(\[\d+\])?$
        - category: auth
          regex: ^secret(\[\d+\])?$
      prefixes:
        - http.request.header.
        - http.response.header.
        - rpc.request.metadata.
        - rpc.response.metadata.
      redaction-strategy: redact
